version: '3.8'

services:
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - worker1
      - worker2
    networks:
      - app-network

  worker1:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - WORKER_PORT=9001
    networks:
      - app-network

  worker2:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - WORKER_PORT=9002
    networks:
      - app-network

networks:
  app-network:
    driver: bridge